/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "mylcd.h"
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	LCDinit();

	LCDputs(LCD_line1,"      Let's     ");
	LCDputs(LCD_line2," The Game Begin ");

	uint32_t count=16;
	//for(int i=0; i<16; i++)
		while(count !=0){
			DelayMs(1000);
			LCDwrite(LCD_cmd, LCD_disp_sft);
			count--;
		}

	LCDwrite(LCD_cmd,LCD_clear);

	return 0;
}
