/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "myled.h"
#include "myswitch.h"
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "mylcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int cnt;
int main(void)
{
	SystemInit();
	LEDInIt(LED_blue);
	Switchinit(SWITCH);
	LCDinit();
	char str[14];


			while(1)
			{
				sprintf(str,"Count = %d",cnt);
				LCDputs(LCD_line1, str);
				while(exti0_flag == 0)
					;

				cnt++;
				LEDblink(LED_blue,200);
				exti0_flag = 0;

			}

	return 0;
}
