/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "myeeprom.h"
#include "myi2c.h"
#include "myuart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[100] ;
	int choice;
	char str2 [100];
	SystemInit();
	UartInit(BAUD_9600);
	EEPROM_Init();
	do
		{
			UartPuts("Menu:\n\r1. Write String to EEPROM\n\r2. Read String from EEPROM\n\n\r");

			UartPuts("Select your choice: ");
			UartGets(str);
			sscanf(str, "%d", &choice);
			switch(choice) {

				case 1:
						UartPuts("Enter the string\n\r");
						UartGets(str2);
						EEPROM_Write(0x0020, (uint8_t*)str2, 32);
						break;

				case 2:
						EEPROM_Read(0x0020, (uint8_t*)str2, 32);
						UartPuts(str2);
						break;

			}
		}while(choice != 0);

		while(1);
		return 0;
}
